name: Test de Acceso Pokedex
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest    
    steps:
    
      - name: Pruebas de acceso al sitio
        uses: ./load-test-action
        with:
            url: https://arroyowal.github.io/Pokedex/
            number-of-requests: 10
            concurrency: 2
